import { SHOW_VITAL_SIGN_FORM, SHOW_PROCEDURE_FORM, SHOW_DISCHARGE_FORM } from './types.js';

export const showFormsFilters = {
  SHOW_VITAL_SIGN_FORM: 'SHOW_VITAL_SIGN_FORM',
  SHOW_PROCEDURE_FORM: 'SHOW_PROCEDURE_FORM',
  SHOW_DISCHARGE_FORM: 'SHOW_DISCHARGE_FORM',
}