export const GET_PATIENTS = 'GET_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const GET_VITALSIGNS = 'GET_VITALSIGNS';
export const ADD_VITALSIGN = 'ADD_VITALSIGN';
export const UPDATE_VITALSIGN = 'UPDATE_VITALSIGN';
export const DELETE_VITALSIGN = 'DELETE_VITALSIGN';

export const GET_PATIENT_DETAILS = 'GET_PATIENT_DETAILS';
 
