export const GET_PATIENTS = 'GET_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const GET_RECORDS = 'GET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';

export const GET_FORMS = 'GET_FORMS';

export const GET_PATIENT_DETAILS = 'GET_PATIENT_DETAILS';

export const SET_FORM_FILTER = 'SET_FORM_FILTER';
export const SHOW_VITAL_SIGN_FORM = 'SHOW_VITAL_SIGN_FORM';
export const SHOW_PROCEDURE_FORM = 'SHOW_PROCEDURE_FORM';
export const SHOW_DISCHARGE_FORM = 'SHOW_DISCHARGE_FORM';
 
