export const GET_PATIENTS = 'GET_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const GET_RECORDS = 'GET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';

export const GET_FORMS = 'GET_FORMS';
export const GET_FORM_DETAILS = 'GET_FORM_DETAILS';
export const GET_VITALSIGN = 'GET_VITALSIGN';

export const GET_PATIENT_DETAILS = 'GET_PATIENT_DETAILS';
 
